#pragma once

#include "CoreMinimal.h"
#include "NativeGameplayTags.h"

namespace BrandNewGamePlayTag
{
	/**
	 * Attribute Tags
	 */
	COREMODULE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Attribute_Primary_Strength);
	COREMODULE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Attribute_Primary_Intelligence);
	COREMODULE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Attribute_Primary_Dexterity);
	COREMODULE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Attribute_Primary_Vitality);
	
	COREMODULE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Attribute_Experience_Level);
	COREMODULE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Attribute_Experience_XP);
	COREMODULE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Attribute_Experience_AttributePoint);

	COREMODULE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Attribute_Secondary_MaxHealth);
	COREMODULE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Attribute_Vital_CurrentHealth);
	COREMODULE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Attribute_Secondary_MaxMana);
	COREMODULE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Attribute_Vital_CurrentMana);
	
	COREMODULE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Attribute_Secondary_PhysicalAttackPower);
	COREMODULE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Attribute_Secondary_MagicAttackPower);
	COREMODULE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Attribute_Secondary_PhysicalDefensePower);
	COREMODULE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Attribute_Secondary_MagicDefensePower);
	COREMODULE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Attribute_Secondary_CriticalChance);
	COREMODULE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Attribute_Secondary_CriticalMagnitude);

	/**
	 * Item Attribute Tag
	 */

	COREMODULE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Attribute_Item_Strength);
	COREMODULE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Attribute_Item_Intelligence);
	COREMODULE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Attribute_Item_Dexterity);
	COREMODULE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Attribute_Item_Vitality);
	
	/**
	 * Input Tags
	 */ 
	COREMODULE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Input_Move);
	COREMODULE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Input_Jump);
	COREMODULE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Input_Look);
	COREMODULE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Input_Walk);
	COREMODULE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Input_Look);
	COREMODULE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Input_Run);
	COREMODULE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Input_Interact);
	COREMODULE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Input_CameraScroll);

	COREMODULE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Input_Ability_Equip);
	COREMODULE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Input_Ability_Unequip);
	COREMODULE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Input_Ability_LockOn);
	
	COREMODULE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Input_Ability_Combo);
	COREMODULE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Input_Ability_Combo_NormalAttack);
	COREMODULE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Input_Ability_SpawnMagicSphere);
	COREMODULE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Input_Ability_FireBall);
	COREMODULE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Input_Ability_Dodge);


	COREMODULE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Input_UI_OpenInGameMenu);
	
	/**
	 * Ability Tags
	 */
	COREMODULE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Ability_Player_Combat);
	COREMODULE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Ability_Player_Combat_EquipWeapon);
	COREMODULE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Ability_Player_Combat_UnequipWeapon);
	COREMODULE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Ability_Player_Combat_NormalAttack);
	COREMODULE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Ability_Player_Combat_SpawnMagicSphere);
	COREMODULE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Ability_Player_Combat_FireBall);
	
	COREMODULE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Ability_Player_Special_Dodge);
	
	COREMODULE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Ability_Player_Utility_LockOn);
	
	COREMODULE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Ability_Enemy_Combat_MeleeAttack);
	COREMODULE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Ability_Enemy_Combat_RangeAttack);
	COREMODULE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Ability_Enemy_Combat_TrackingShard);
	COREMODULE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Ability_Enemy_Combat_ShockLanding);
	COREMODULE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Ability_Enemy_Combat_JumpAttack);
	COREMODULE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Ability_Enemy_Combat_Roaring);
	
	COREMODULE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Ability_Enemy_Utility_ItemDrop);
	
	COREMODULE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Ability_Shared_React_Hit);
	COREMODULE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Ability_Shared_React_Death);

	/**
	 * Event Tags
	 */
	COREMODULE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Event_EquipWeapon);
	COREMODULE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Event_UnequipWeapon);
	
	// 애니메이션에서 공격 종료 지점을 알리는 태그 (이후 나머지 애니메이션 재생)
	COREMODULE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Event_Attack_End);
	
	COREMODULE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Event_ProjectileSpawn);
	
	COREMODULE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Event_Hit_Melee);

	COREMODULE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Event_HitReact);
	COREMODULE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Event_HitReact_Front);
	COREMODULE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Event_HitReact_Back);
	COREMODULE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Event_HitReact_Left);
	COREMODULE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Event_HitReact_Right);
	
	COREMODULE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Event_ItemDrop);

	/**
	 * Damage Tags
	 */
	COREMODULE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Damage_Type_Physical);
	COREMODULE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Damage_Type_Magic);
	
	COREMODULE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Damage_Element_NoneElemental);
	COREMODULE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Damage_Element_Fire);
	COREMODULE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Damage_Element_Ice);
	COREMODULE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Damage_Element_Light);
	COREMODULE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Damage_Element_Darkness);
	
	/**
	 * Status Tags
	 */
	COREMODULE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Status_Shared_Hit);
	COREMODULE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Status_Shared_Dead);
	COREMODULE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Status_Shared_Strafing);
	COREMODULE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Status_Shared_Invincible);
	COREMODULE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Status_Shared_SuperArmor);
	
	COREMODULE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Status_Player_LockOn);
	COREMODULE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Status_Player_Fire);
	COREMODULE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Status_Player_Dodging);

	/**
	 * Gameplay Cue Tags
	 */
	COREMODULE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(GameplayCue_Widget_Damage_Normal);
	
	COREMODULE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(GameplayCue_Effect_GroundWarning);
	COREMODULE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(GameplayCue_Effect_ArcaneShard);
	COREMODULE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(GameplayCue_Effect_LandingImpact);

	/**
	 * Block Tags
	 */
	COREMODULE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Block_Player_Movement);
	COREMODULE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Block_Player_GageChange);
	
	
}