#pragma once

#include "CoreMinimal.h"
#include "NativeGameplayTags.h"

namespace BrandNewGamePlayTag
{
	COREMODULE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Input_Move);
	COREMODULE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Input_Jump);
	COREMODULE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Input_Look);
	COREMODULE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Input_Walk);
	COREMODULE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Input_Look);
	COREMODULE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Input_Run);
	
	
	
}